version: '2'
services:
    node:
        image: registry.thinknet.co.th/sredev/node:20.10
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/src/app
        command: ['/bin/sh', '-c', 'cd client && yarn install && yarn dev']
        # environment:
    # jaeger:
    #     image: jaegertracing/all-in-one:1.25
    #     environment:
    #     - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    #     ports:
    #     - 5775:5775/udp
    #     - 6831:6831/udp
    #     - 6832:6832/udp
    #     - 5778:5778
    #     - 16686:16686
    #     - 14268:14268
    #     - 14250:14250
    #     - 9411:9411

networks:
    default:
        external:
            name: microservicenetwork